/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellCriteresRouteImport } from './routes/_shell.criteres'
import { Route as ShellDashboardRouteImport } from './routes/_shell.dashboard'
import { Route as ShellAppelsOffresIndexRouteImport } from './routes/_shell.appels-offres.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellCriteresRoute = ShellCriteresRouteImport.update({
  id: '/criteres',
  path: '/criteres',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDashboardRoute = ShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAppelsOffresIndexRoute = ShellAppelsOffresIndexRouteImport.update({
  id: '/appels-offres/',
  path: '/appels-offres/',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/criteres': typeof ShellCriteresRoute
  '/dashboard': typeof ShellDashboardRoute
  '/appels-offres/': typeof ShellAppelsOffresIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/criteres': typeof ShellCriteresRoute
  '/dashboard': typeof ShellDashboardRoute
  '/appels-offres': typeof ShellAppelsOffresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/criteres': typeof ShellCriteresRoute
  '/_shell/dashboard': typeof ShellDashboardRoute
  '/_shell/appels-offres/': typeof ShellAppelsOffresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/criteres' | '/dashboard' | '/appels-offres/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/criteres' | '/dashboard' | '/appels-offres'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/_shell/criteres'
    | '/_shell/dashboard'
    | '/_shell/appels-offres/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/criteres': {
      id: '/_shell/criteres'
      path: '/criteres'
      fullPath: '/criteres'
      preLoaderRoute: typeof ShellCriteresRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/dashboard': {
      id: '/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ShellDashboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/appels-offres/': {
      id: '/_shell/appels-offres/'
      path: '/appels-offres'
      fullPath: '/appels-offres/'
      preLoaderRoute: typeof ShellAppelsOffresIndexRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellCriteresRoute: typeof ShellCriteresRoute
  ShellDashboardRoute: typeof ShellDashboardRoute
  ShellAppelsOffresIndexRoute: typeof ShellAppelsOffresIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellCriteresRoute: ShellCriteresRoute,
  ShellDashboardRoute: ShellDashboardRoute,
  ShellAppelsOffresIndexRoute: ShellAppelsOffresIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
